name: Flatpak

on:
  push:
    branches:
      - main
  workflow_call:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    container:
      image: bilelmoussaoui/flatpak-github-actions:freedesktop-23.08
      options: --privileged
    steps:
      - uses: actions/checkout@v4
      - uses: flatpak/flatpak-github-actions/flatpak-builder@v6
        with:
          bundle: so.notion.Calendar.flatpak
          manifest-path: so.notion.Calendar.yaml
